[package]
name = "aoc-2020-4"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@sensirion.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
